fix openeo_driver version after upgrade to pip 24.1
+ pip install '.[dev]'
Looking in indexes: https://puppet:****@artifactory.vgt.vito.be/artifactory/api/pypi/python-packages/simple
Processing /var/lib/jenkins/workspace/openEO/openeo-integrationtests/openeo-geopyspark-integrationtests
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Requested openeo-geopyspark-integrationtests==0.0.0 from file:///var/lib/jenkins/workspace/openEO/openeo-integrationtests/openeo-geopyspark-integrationtests has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    openeo_driver>=0.39.1a1.*
                 ~~~~~~~~~~~^