fixed tests after removal of legacy DataCube.graph
    def _dump_process_graph(cube: Union[DataCube, ImageCollectionClient], tmp_path: Path, name="process_graph.json"):
        """Dump a cube's process graph as json to a temp file"""
        with (tmp_path / name).open("w") as fp:
>           json.dump(cube.graph, fp, indent=2)
E           AttributeError: 'DataCube' object has no attribute 'graph'