fix test_sentinel_hub_execute_batch
FAILED openeo-geopyspark-integrationtests/tests/test_integration.py::test_sentinel_hub_execute_batch[1.1.0] - openeo.rest.OpenEoClientException: DataCube.download() with explicit output format GTiff, but the process graph already has `save_result` node(s) which is ambiguous and should not be combined.